package com.lec.ex04_newException;

public class AccountMain {
	public static void main(String[] args) {
//		Account ppl1 = new Account();
//		Account ppl2 = new Account("1","辫");
//		ppl1.deposit(4000);
//		ppl1.setOwnerName("全");
//		ppl1.setAccountNo("100-100");
//		ppl2.setAccountNo("100-101");
//		ppl2.deposit(5000000);
//		ppl2.withdraw(2800000);
//		ppl1.info();
//		ppl2.info();
		
		Account hong = new Account("110-1", "全辨悼", 50000);
		Account hong1 = new Account("110-2", "全老");
		Account hong2 = new Account();
		hong2.setAccountNo("110-9");
		hong2.setOwnerName("脚辨悼");
		hong2.deposit(40000);
		hong.deposit(10000);
		System.out.println(hong);
		try {
			hong.withdraw(4000);
			
		}catch(Exception e) {
			System.out.println(e.getMessage());
		}
		hong1.withdraw(1);
		System.out.println(hong1);
		hong2.deposit(10000);
		hong2.withdraw(20000);
		System.out.println(hong2);

	}
	
	
}
